@startuml Game Model


package "Model"{
    game "1" *-- "2" player: contains
    game "1" *-- "1" matrix: contains
    game "1" *-- "1" configurations : contains
    matrix "1" *-- "size" matrixRow: contains
    matrixRow "1" *-- "size" matrixCell: contains
    ' matrix "1" - "1" board:contains
    ' board "1" *-- "size" boardRow: contains
    ' boardRow "1" *-- "size" boardCell: contains
    ' matrixCell <. boardCell: Dependency
    game "1" -- "1" timerM: contains
}

class game {
    Number turn
    player playerTurn
    void setBoardSize()
    void clicked(Number i, Number j)
    void moveAnalyze()
}

class player{
    String name
    String color
    Bool hints
    Number id
    String getColor()
}

class configurations{
    Number size
    Bool bgImage
    String bgColor
}

class timerM{
    Number elapsed
    Boolean running
}

class matrix{
    Array[] cells
    setCell()
}

class matrixRow{
    matrixCell cell
    getCell()
}

class matrixCell{
    Bool claimed
    player owner
    Number turnClaimed
    player getOwner()
}



@enduml